# Prometheus â€” scrape Keycloak metrics (management port 9000)
global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: keycloak
    static_configs:
      - targets: ["keycloak:9000"]
        labels:
          namespace: keycloak
          container: keycloak
    metrics_path: /metrics

  - job_name: keycloak-session-exporter
    static_configs:
      - targets: ["keycloak-session-exporter:9091"]
        labels:
          namespace: keycloak
          container: keycloak-session-exporter
    metrics_path: /metrics
